### PR TITLE
Add moderation team charter

### PR DESCRIPTION
**Pull request by technetos**
This PR introduces a draft of the Moderation team charter. This document is intended to provide a foundation for the Moderation team to build upon in the future and define basic policy and structure for the team. 

[Rendered](https://github.com/rust-lang/moderation-team/blob/0c117fffd7c59bf29b247c62ee8d0c469edbf58f/moderation-team-charter.md)

### CODE REVIEW

**Comment by Manishearth** [comment]
Those internal links probably only work if this PR is to the rust-lang/governance repo?

But this looks great!

**Comment by technetos** [comment]
> Those internal links probably only work if this PR is to the rust-lang/governance repo?

Yeah thats correct. Additionally the links to the role descriptions on hackmd for team lead and council delegate will need to be updated once the council sets up a place for policy documentation.

**Comment by llogiq** [comment]
I feel we should have a provision for removing a team member if the rest of the team can show that they are no longer fitting the role. The burden of proof would still lie with the rest of the mod team but we shouldn't allow a case where a moderator stays on the team despite not doing the work properly.

**Comment by khionu** [comment]
This is more meant to capture the status quo. Things like team membership and membership structure are among what we're wanting to address after the governance RFC

**Review by khionu — APPROVED** [review]

**Pull request merged**
